# This is a basic workflow to help you get started with Actions

name: Pantheon Remote Branch Push

# Repo Sync on Push
on: 
  push:
    branches-ignore:
      - master 
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Git Sync Action
      uses: wei/git-sync@v2.0.0
      with:
        source_repo: "https://github.com/mpaladino/drupal-project.git"
        source_branch: "refs/remotes/source/*"
        destination_repo: ${{ secrets.REMOTE_PANTHEON_REPO }}
        destination_branch: "refs/heads/*"
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
